# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_KIRIN_HW_VOTE)	+= kirin-hw-vote.o
obj-$(CONFIG_KIRIN_PERI_DVFS)	+= kirin-peri-dvfs.o
obj-$(CONFIG_KUNPENG_HCCS)	+= kunpeng_hccs.o
obj-$(CONFIG_L410_DEADMAN)	+= l410-deadman.o
obj-$(CONFIG_KIRIN990_SUSPEND)	+= kirin990-sr.o
obj-$(CONFIG_L410_PERF)		+= l410-perf.o
